#! /usr/bin/perl -w
#
#	@(#)$Id: BugReport version /main/6 2000-02-01 13:45:37 $
#
#	Produce output for a Informix Database Driver for Perl Version 0.97004 (2000-02-10) Bug Report
#
#	Portions Copyright (C) 1999 Jonathan Leffler
#	Portions Copyright (C) 2000 Informix Software Inc
#
# * See Notes/bug.reports for lots more details.
# * By default (no arguments), produces just the most basic bug
#   reporting info - versions and platform and environment.
# * If given an argument A or B or C, produces the info for that
#   type of bug report.
# * If given an argument D and one or more specific test names,
#   produces the info for a type D bug report.
# * Assuming you use a Bourne/Korn/BornAgain shell, it is quite
#   reasonable to build DBD::Informix using:
#       perl BugReport C 2>&1 | tee bugreport.out

use DBD::Informix::TechSupport;
bug_report(@ARGV);
