#! /usr/bin/perl
#
#   @(#)$Id: ItWorks,v 100.4 2002/02/08 22:48:49 jleffler Exp $
#
#   Generate a report that Informix Database Driver for Perl Version 1.04.PC1 (2002-11-21) works
#
#   Copyright 1999 Jonathan Leffler
#   Copyright 2000 Informix Software Inc
#   Copyright 2002 IBM

### This trick was more or less standard with Perl 4 ###
eval "exec perl $0 $*"
		if $running_under_some_shell;

use DBD::Informix::TechSupport;
it_works;
